[package]
name = "revault_scripts"
version = "0.1.0"
authors = ["Antoine Poinsot <darosior@protonmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
bitcoin = "0.23.0"
secp256k1 = { version = "0.17.2" }
miniscript = { version = "1.0.0", features = ["compiler"] }
