[package]
name = "revault_scripts"
version = "0.1.0"
authors = ["Antoine Poinsot <darosior@protonmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
bitcoin = "0.24"
miniscript = "2.0.0"
revault_tx = { git = "https://github.com/re-vault/revault_tx" }
